name: restaurant_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  google_fonts: 2.1.0
  font_awesome_flutter: 9.2.0
  carousel_slider: 4.0.0
  lottie: 1.2.1
  path: 1.8.0
  sqflite: 2.0.0+4
  get_storage: 2.0.3
  fab_circular_menu: 1.0.2
  intl: 0.17.0
  android_alarm_manager: 2.0.2
  flutter_local_notifications: 9.1.1
  rxdart: 0.27.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_native_splash: 1.3.1
  flutter_launcher_icons: 0.9.2
  mockito: 5.0.16
  build_runner: 2.1.5
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path: assets/images/img_logo.png
  android: true
  ios: true

flutter_native_splash: 
  color: '#FFFFFF'
  image: assets/images/img_logo.png
  android: true
  ios: true

flutter: 
  assets: 
    - assets/models/
    - assets/images/
    - assets/animations/
  uses-material-design: true

